# Site settings
title: DATA 606 - Spring 2016
email: jason.bryer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This course covers basic techniques in probability and statistics that are 
  important in the field of data analytics. Discrete probability models, 
  sampling from infinite and finite populations, statistical distributions, 
  basic Bayesian statistics, and non-parametric statistical techniques for 
  categorical data are covered in this course. Each of these statistical 
  concepts will be applied in a variety of real-world scenarios through the 
  use of case studies and customized data sets.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://data606.net" # the base hostname & protocol for your site
twitter_username: jbryer
github_username:  jbryer

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: ""
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
